auth:
  database: ${postgres_database}
  username: ${postgres_username}
  password: ${postgres_password}

primary:
  persistence:
    enabled: true
    size: ${storage_size}

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

  service:
    type: ClusterIP