replicaCount: 1

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: "notebook"

image:
  repository: agilesolutions/notebook
  tag: 1.0.13
  pullPolicy: IfNotPresent

imagePullSecrets:
  name: dockerhub-secret
  create: true
  registry: https://index.docker.io/v1/
  username: "agilesolutions"
  password: ""
  email: "robert.rong@agile-solutions.ch"

database:
  secret:
    create: true
    name: notebook-db
    username: notebook
    password: notebook

app:
  enabled: true

service:
#  type: ClusterIP
# Docker Desktop will automatically bind that port to your Windows machine's localhost
  type: LoadBalancer
  port: 8080

ingress:
  enabled: false
  className: traefik
  host: notbook.agilesolutions.com
  clusterIssuer: letsencrypt-production
  tlsSecretName: notebook-tls

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

config:
  SPRING_PROFILES_ACTIVE: kubernetes
  LOG_LEVEL: INFO
  OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://alloy.monitoring.svc.cluster.local:4318/v1/traces
  OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: http://alloy.monitoring.svc.cluster.local:4318/v1/metrics
  OTEL_EXPORTER_OTLP_LOGS_ENDPOINT: http://alloy.monitoring.svc.cluster.local:4318/v1/logs
  OTEL_TRACES_SAMPLER_ARG: 1.0