apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "notebook.fullname" . }}
data:
  SPRING_PROFILES_ACTIVE: {{ .Values.config.SPRING_PROFILES_ACTIVE | quote }}
  LOG_LEVEL: {{ .Values.config.LOG_LEVEL | quote }}
  OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: {{ .Values.config.OTEL_EXPORTER_OTLP_TRACES_ENDPOINT | quote }}
  OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: {{ .Values.config.OTEL_EXPORTER_OTLP_METRICS_ENDPOINT | quote }}
  OTEL_EXPORTER_OTLP_LOGS_ENDPOINT: {{ .Values.config.OTEL_EXPORTER_OTLP_LOGS_ENDPOINT | quote }}
  OTEL_TRACES_SAMPLER_ARG: {{ .Values.config.OTEL_TRACES_SAMPLER_ARG | quote }}

