apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "notebook.fullname" . }}
data:
  SPRING_PROFILES_ACTIVE: {{ .Values.config.SPRING_PROFILES_ACTIVE | quote }}
  LOG_LEVEL: {{ .Values.config.LOG_LEVEL | quote }}

